---
- name : install Docker
  hosts: vm 
  #become: true
  vars:
     ansible_ssh_extra_args: "-o StrictHostKeyChecking=no"
  tasks: 
    - name : install Docker 
      roles:
         role: jimbo8098.windows_docker_role
         reboots_allowed: true
         