appName: emailservice
appImage: gcr.io/google-samples/microservices-demo/emailservice
appVersion: v0.6.0
appReplicas: 2
containerPort: 8080
containerEnvVars:
  - name: PORT
    value: "8080"
  - name: DISABLE_TRACING
    value: "1"
  - name: DISABLE_PROFILER
    value: "1"

servicePort: 5000
