---
- name: install Docker
  hosts: vm
  become: true
  vars:
    ansible_ssh_extra_args: "-o StrictHostKeyChecking=no"
  tasks: 
  - name: update the packages
    apt: 
     update_cache: yes #apt get update
  - name: install packages 
    apt: 
     name: 
          - ca-certificates
          - curl 
          - gnupg
          - lsb-release
          - apt-transport-https
     state: latest 
  - name: Add the Docker official GPG key 
    apt_key: 
      url: https://download.docker.com/linux/ubuntu/gpg
      state: present
  - name: set up the repository 
    apt_repository:
      repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_lsb.codename }} stable
      state: present
  - name: update the package again 
    apt:
      update_cache: yes
  - name: install Docker
    apt:
       name: 
         - docker-ce 
         - docker-ce-cli 
         - containerd.io 
         - docker-buildx-plugin 
         - docker-compose-plugin
       state: latest 